import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>
          더줄게 | 세상의 모든 알바! 일자리 & 아르바이트 구인 구직 사이트
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/thejulgeFavicon.ico" />
      </Head>
    </>
  );
}
